# coding: utf-8

"""
    ESCO REST API Docs

    The ESCO REST API exposes ESCO as a simple, RESTful API.<br /><br /> <a href=\"esco-api-openapi-v3.yml\">Open API v3 definition</a>  # noqa: E501

    OpenAPI spec version: 1.0.12
    Contact: EMPL-ESCO-SECRETARIAT@ec.europa.eu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.single_concept_api import SingleConceptApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSingleConceptApi(unittest.TestCase):
    """SingleConceptApi unit test stubs"""

    def setUp(self):
        self.api = SingleConceptApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_resource_concept_get(self):
        """Test case for resource_concept_get

        Get concept  # noqa: E501
        """
        pass

    def test_resource_occupation_get(self):
        """Test case for resource_occupation_get

        Get occupation  # noqa: E501
        """
        pass

    def test_resource_skill_get(self):
        """Test case for resource_skill_get

        Get skill  # noqa: E501
        """
        pass

    def test_resource_taxonomy_get(self):
        """Test case for resource_taxonomy_get

        Get concept scheme  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
