# coding: utf-8

"""
    ESCO REST API Docs

    The ESCO REST API exposes ESCO as a simple, RESTful API.<br /><br /> <a href=\"esco-api-openapi-v3.yml\">Open API v3 definition</a>  # noqa: E501

    OpenAPI spec version: 1.0.12
    Contact: EMPL-ESCO-SECRETARIAT@ec.europa.eu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.skill_links import SkillLinks  # noqa: E501
from swagger_client.rest import ApiException


class TestSkillLinks(unittest.TestCase):
    """SkillLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSkillLinks(self):
        """Test SkillLinks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.skill_links.SkillLinks()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
