# coding: utf-8

"""
    ESCO REST API Docs

    The ESCO REST API exposes ESCO as a simple, RESTful API.<br /><br /> <a href=\"esco-api-openapi-v3.yml\">Open API v3 definition</a>  # noqa: E501

    OpenAPI spec version: 1.0.12
    Contact: EMPL-ESCO-SECRETARIAT@ec.europa.eu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.history_api import HistoryApi  # noqa: E501
from swagger_client.rest import ApiException


class TestHistoryApi(unittest.TestCase):
    """HistoryApi unit test stubs"""

    def setUp(self):
        self.api = HistoryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_conversion_concept_get(self):
        """Test case for conversion_concept_get

        Get Converted Concept  # noqa: E501
        """
        pass

    def test_conversion_occupation_get(self):
        """Test case for conversion_occupation_get

        Get Converted Occupation  # noqa: E501
        """
        pass

    def test_conversion_skill_get(self):
        """Test case for conversion_skill_get

        Get Converted Skill  # noqa: E501
        """
        pass

    def test_history_get(self):
        """Test case for history_get

        Get history  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
