# coding: utf-8

"""
    ESCO REST API Docs

    The ESCO REST API exposes ESCO as a simple, RESTful API.<br /><br /> <a href=\"esco-api-openapi-v3.yml\">Open API v3 definition</a>  # noqa: E501

    OpenAPI spec version: 1.0.12
    Contact: EMPL-ESCO-SECRETARIAT@ec.europa.eu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.search_api import SearchApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSearchApi(unittest.TestCase):
    """SearchApi unit test stubs"""

    def setUp(self):
        self.api = SearchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_search_get(self):
        """Test case for search_get

        Full text search - complete mode  # noqa: E501
        """
        pass

    def test_search_quick_mode(self):
        """Test case for search_quick_mode

        Full text search - quick mode  # noqa: E501
        """
        pass

    def test_suggest2_get(self):
        """Test case for suggest2_get

        Suggest2  # noqa: E501
        """
        pass

    def test_suggest_get(self):
        """Test case for suggest_get

        Suggest  # noqa: E501
        """
        pass

    def test_terms_get(self):
        """Test case for terms_get

        Terms  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
