# coding: utf-8

"""
    ESCO REST API Docs

    The ESCO REST API exposes ESCO as a simple, RESTful API.<br /><br /> <a href=\"esco-api-openapi-v3.yml\">Open API v3 definition</a>  # noqa: E501

    OpenAPI spec version: 1.0.12
    Contact: EMPL-ESCO-SECRETARIAT@ec.europa.eu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "swagger-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="ESCO REST API Docs",
    author_email="EMPL-ESCO-SECRETARIAT@ec.europa.eu",
    url="",
    keywords=["Swagger", "ESCO REST API Docs"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    The ESCO REST API exposes ESCO as a simple, RESTful API.&lt;br /&gt;&lt;br /&gt; &lt;a href&#x3D;\&quot;esco-api-openapi-v3.yml\&quot;&gt;Open API v3 definition&lt;/a&gt;  # noqa: E501
    """
)
