# coding: utf-8

"""
    ESCO REST API Docs

    The ESCO REST API exposes ESCO as a simple, RESTful API.<br /><br /> <a href=\"esco-api-openapi-v3.yml\">Open API v3 definition</a>  # noqa: E501

    OpenAPI spec version: 1.0.12
    Contact: EMPL-ESCO-SECRETARIAT@ec.europa.eu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from swagger_client.models.resources import Resources  # noqa: F401,E501

class Concepts(Resources):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'embedded': 'dict(str, Concept)'
    }
    if hasattr(Resources, "swagger_types"):
        swagger_types.update(Resources.swagger_types)

    attribute_map = {
        'embedded': '_embedded'
    }
    if hasattr(Resources, "attribute_map"):
        attribute_map.update(Resources.attribute_map)

    def __init__(self, embedded=None, *args, **kwargs):  # noqa: E501
        """Concepts - a model defined in Swagger"""  # noqa: E501
        self._embedded = None
        self.discriminator = None
        if embedded is not None:
            self.embedded = embedded
        Resources.__init__(self, *args, **kwargs)

    @property
    def embedded(self):
        """Gets the embedded of this Concepts.  # noqa: E501


        :return: The embedded of this Concepts.  # noqa: E501
        :rtype: dict(str, Concept)
        """
        return self._embedded

    @embedded.setter
    def embedded(self, embedded):
        """Sets the embedded of this Concepts.


        :param embedded: The embedded of this Concepts.  # noqa: E501
        :type: dict(str, Concept)
        """

        self._embedded = embedded

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Concepts, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Concepts):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
