# coding: utf-8

"""
    ESCO REST API Docs

    The ESCO REST API exposes ESCO as a simple, RESTful API.<br /><br /> <a href=\"esco-api-openapi-v3.yml\">Open API v3 definition</a>  # noqa: E501

    OpenAPI spec version: 1.0.12
    Contact: EMPL-ESCO-SECRETARIAT@ec.europa.eu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from swagger_client.models.hal_object import HalObject  # noqa: F401,E501

class Relation(HalObject):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'total': 'int',
        'offset': 'int',
        'limit': 'int',
        'language': 'str',
        'uri': 'str',
        'relation': 'str',
        'links': 'RelationLinks',
        'embedded': 'RelationEmbedded'
    }
    if hasattr(HalObject, "swagger_types"):
        swagger_types.update(HalObject.swagger_types)

    attribute_map = {
        'total': 'total',
        'offset': 'offset',
        'limit': 'limit',
        'language': 'language',
        'uri': 'uri',
        'relation': 'relation',
        'links': '_links',
        'embedded': '_embedded'
    }
    if hasattr(HalObject, "attribute_map"):
        attribute_map.update(HalObject.attribute_map)

    def __init__(self, total=None, offset=0, limit=None, language=None, uri=None, relation=None, links=None, embedded=None, *args, **kwargs):  # noqa: E501
        """Relation - a model defined in Swagger"""  # noqa: E501
        self._total = None
        self._offset = None
        self._limit = None
        self._language = None
        self._uri = None
        self._relation = None
        self._links = None
        self._embedded = None
        self.discriminator = None
        self.total = total
        if offset is not None:
            self.offset = offset
        if limit is not None:
            self.limit = limit
        self.language = language
        self.uri = uri
        self.relation = relation
        if links is not None:
            self.links = links
        if embedded is not None:
            self.embedded = embedded
        HalObject.__init__(self, *args, **kwargs)

    @property
    def total(self):
        """Gets the total of this Relation.  # noqa: E501

        The total number of related resources found.  # noqa: E501

        :return: The total of this Relation.  # noqa: E501
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this Relation.

        The total number of related resources found.  # noqa: E501

        :param total: The total of this Relation.  # noqa: E501
        :type: int
        """
        if total is None:
            raise ValueError("Invalid value for `total`, must not be `None`")  # noqa: E501

        self._total = total

    @property
    def offset(self):
        """Gets the offset of this Relation.  # noqa: E501

        The offset of the returned resources. Supports paging where the 'offset' specifies the page number (zero-based numbering).  # noqa: E501

        :return: The offset of this Relation.  # noqa: E501
        :rtype: int
        """
        return self._offset

    @offset.setter
    def offset(self, offset):
        """Sets the offset of this Relation.

        The offset of the returned resources. Supports paging where the 'offset' specifies the page number (zero-based numbering).  # noqa: E501

        :param offset: The offset of this Relation.  # noqa: E501
        :type: int
        """

        self._offset = offset

    @property
    def limit(self):
        """Gets the limit of this Relation.  # noqa: E501

        The maximum number of returned resources. Supports paging where the 'limit' specifies the maximum page size  # noqa: E501

        :return: The limit of this Relation.  # noqa: E501
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this Relation.

        The maximum number of returned resources. Supports paging where the 'limit' specifies the maximum page size  # noqa: E501

        :param limit: The limit of this Relation.  # noqa: E501
        :type: int
        """

        self._limit = limit

    @property
    def language(self):
        """Gets the language of this Relation.  # noqa: E501

        The default language of the response.  # noqa: E501

        :return: The language of this Relation.  # noqa: E501
        :rtype: str
        """
        return self._language

    @language.setter
    def language(self, language):
        """Sets the language of this Relation.

        The default language of the response.  # noqa: E501

        :param language: The language of this Relation.  # noqa: E501
        :type: str
        """
        if language is None:
            raise ValueError("Invalid value for `language`, must not be `None`")  # noqa: E501

        self._language = language

    @property
    def uri(self):
        """Gets the uri of this Relation.  # noqa: E501

        The uri of the resource to get related resources from.  # noqa: E501

        :return: The uri of this Relation.  # noqa: E501
        :rtype: str
        """
        return self._uri

    @uri.setter
    def uri(self, uri):
        """Sets the uri of this Relation.

        The uri of the resource to get related resources from.  # noqa: E501

        :param uri: The uri of this Relation.  # noqa: E501
        :type: str
        """
        if uri is None:
            raise ValueError("Invalid value for `uri`, must not be `None`")  # noqa: E501

        self._uri = uri

    @property
    def relation(self):
        """Gets the relation of this Relation.  # noqa: E501

        The relation to query related resources for.  # noqa: E501

        :return: The relation of this Relation.  # noqa: E501
        :rtype: str
        """
        return self._relation

    @relation.setter
    def relation(self, relation):
        """Sets the relation of this Relation.

        The relation to query related resources for.  # noqa: E501

        :param relation: The relation of this Relation.  # noqa: E501
        :type: str
        """
        if relation is None:
            raise ValueError("Invalid value for `relation`, must not be `None`")  # noqa: E501

        self._relation = relation

    @property
    def links(self):
        """Gets the links of this Relation.  # noqa: E501


        :return: The links of this Relation.  # noqa: E501
        :rtype: RelationLinks
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this Relation.


        :param links: The links of this Relation.  # noqa: E501
        :type: RelationLinks
        """

        self._links = links

    @property
    def embedded(self):
        """Gets the embedded of this Relation.  # noqa: E501


        :return: The embedded of this Relation.  # noqa: E501
        :rtype: RelationEmbedded
        """
        return self._embedded

    @embedded.setter
    def embedded(self, embedded):
        """Sets the embedded of this Relation.


        :param embedded: The embedded of this Relation.  # noqa: E501
        :type: RelationEmbedded
        """

        self._embedded = embedded

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Relation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Relation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
