# coding: utf-8

"""
    ESCO REST API Docs

    The ESCO REST API exposes ESCO as a simple, RESTful API.<br /><br /> <a href=\"esco-api-openapi-v3.yml\">Open API v3 definition</a>  # noqa: E501

    OpenAPI spec version: 1.0.12
    Contact: EMPL-ESCO-SECRETARIAT@ec.europa.eu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from swagger_client.models.base_concept import BaseConcept  # noqa: F401,E501

class Taxonomy(BaseConcept):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'links': 'TaxonomyLinks'
    }
    if hasattr(BaseConcept, "swagger_types"):
        swagger_types.update(BaseConcept.swagger_types)

    attribute_map = {
        'links': '_links'
    }
    if hasattr(BaseConcept, "attribute_map"):
        attribute_map.update(BaseConcept.attribute_map)

    def __init__(self, links=None, *args, **kwargs):  # noqa: E501
        """Taxonomy - a model defined in Swagger"""  # noqa: E501
        self._links = None
        self.discriminator = None
        if links is not None:
            self.links = links
        BaseConcept.__init__(self, *args, **kwargs)

    @property
    def links(self):
        """Gets the links of this Taxonomy.  # noqa: E501


        :return: The links of this Taxonomy.  # noqa: E501
        :rtype: TaxonomyLinks
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this Taxonomy.


        :param links: The links of this Taxonomy.  # noqa: E501
        :type: TaxonomyLinks
        """

        self._links = links

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Taxonomy, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Taxonomy):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
