# coding: utf-8

"""
    ESCO REST API Docs

    The ESCO REST API exposes ESCO as a simple, RESTful API.<br /><br /> <a href=\"esco-api-openapi-v3.yml\">Open API v3 definition</a>  # noqa: E501

    OpenAPI spec version: 1.0.12
    Contact: EMPL-ESCO-SECRETARIAT@ec.europa.eu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TextNode(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'literal': 'str',
        'mimetype': 'str'
    }

    attribute_map = {
        'literal': 'literal',
        'mimetype': 'mimetype'
    }

    def __init__(self, literal=None, mimetype=None):  # noqa: E501
        """TextNode - a model defined in Swagger"""  # noqa: E501
        self._literal = None
        self._mimetype = None
        self.discriminator = None
        self.literal = literal
        self.mimetype = mimetype

    @property
    def literal(self):
        """Gets the literal of this TextNode.  # noqa: E501

        The text snippet.  # noqa: E501

        :return: The literal of this TextNode.  # noqa: E501
        :rtype: str
        """
        return self._literal

    @literal.setter
    def literal(self, literal):
        """Sets the literal of this TextNode.

        The text snippet.  # noqa: E501

        :param literal: The literal of this TextNode.  # noqa: E501
        :type: str
        """
        if literal is None:
            raise ValueError("Invalid value for `literal`, must not be `None`")  # noqa: E501

        self._literal = literal

    @property
    def mimetype(self):
        """Gets the mimetype of this TextNode.  # noqa: E501

        The mimetype of the text snippet. Possible values are: 'plain/text' or 'text/html'  # noqa: E501

        :return: The mimetype of this TextNode.  # noqa: E501
        :rtype: str
        """
        return self._mimetype

    @mimetype.setter
    def mimetype(self, mimetype):
        """Sets the mimetype of this TextNode.

        The mimetype of the text snippet. Possible values are: 'plain/text' or 'text/html'  # noqa: E501

        :param mimetype: The mimetype of this TextNode.  # noqa: E501
        :type: str
        """
        if mimetype is None:
            raise ValueError("Invalid value for `mimetype`, must not be `None`")  # noqa: E501

        self._mimetype = mimetype

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TextNode, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TextNode):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
